name: HawkEye
main: uk.co.oliwali.HawkEye.HawkEye
author: oliverw92
version: 1.0.3
description: Track those griefers like a bird of prey!
softdepend: [WorldEdit,Spout,PermissionsEx,Permissions,GroupManager]
commands:
  hawk:
    description: Track those griefers like a bird of prey!
    aliases: [hawkeye,he,hk,ha]
    usage: /<command> help
permissions:
    hawkeye.*:
        description: Gives access to all HawkEye commands
        children:
            hawkeye.search: true
            hawkeye.tpto: true
            hawkeye.rollback: true
            hawkeye.tool: true
            hawkeye.notify: true
            hawkeye.preview: true