name: DataLog
main: uk.co.oliwali.DataLog.DataLog
author: oliverw92
version: 1.4.0
description: Advanced Data Logging
softdepend: [WorldEdit,Spout]
commands:
  datalog:
    description: Advanced Data Logging
    aliases: dl
    usage: /<command> help
