name: HawkEye
main: uk.co.oliwali.HawkEye.HawkEye
author: oliverw92
version: 1.0.0
description: Track those griefers like a bird of prey!
softdepend: [WorldEdit,Spout,PermissionsEx,Permissions,GroupManager]
commands:
  hawk:
    description: Track those griefers like a bird of prey!
    aliases: [hawkeye,he]
    usage: /<command> help
